name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Make sure you have done the following
      options:
        - label: I have updated to the latest version of the plugin.
          required: true
        - label:
            I have read about the [breaking changes in version 1.0 of the
            plugin](https://github.com/chrisgrieser/nvim-tinygit#breaking-changes-in-v10).
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of the bug.
    validations: { required: true }
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant screenshot
      description:
        If applicable, add screenshots or a screen recording to help explain your problem.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To reproduce
      description: Steps to reproduce the problem
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
  - type: textarea
    id: version-info
    attributes:
      label: neovim version
      render: Text
    validations: { required: true }
